# Generated by Django 4.2.4 on 2024-04-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('stadium_name', models.CharField(default='Stadium', max_length=100)),
                ('stadium_capacity', models.IntegerField(default=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Lineup Name', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=17)),
                ('nationality', models.CharField(default='Unknown', max_length=50)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Right Back', 'Right Back'), ('Left Back', 'Left Back'), ('Center Back', 'Center Back'), ('Right Midfielder', 'Right Midfielder'), ('Central Midfielder', 'Central Midfielder'), ('Left Midfielder', 'Left Midfielder'), ('Attacking Midfielder', 'Attacking Midfielder'), ('Center Forward', 'Center Forward')], default='Unknown', max_length=50)),
                ('player_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('stamina', models.IntegerField(blank=True, null=True)),
                ('pace', models.IntegerField(blank=True, null=True)),
                ('marking', models.IntegerField(blank=True, null=True)),
                ('tackling', models.IntegerField(blank=True, null=True)),
                ('work_rate', models.IntegerField(blank=True, null=True)),
                ('positioning', models.IntegerField(blank=True, null=True)),
                ('passing', models.IntegerField(blank=True, null=True)),
                ('crossing', models.IntegerField(blank=True, null=True)),
                ('dribbling', models.IntegerField(blank=True, null=True)),
                ('ball_control', models.IntegerField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('finishing', models.IntegerField(blank=True, null=True)),
                ('long_range', models.IntegerField(blank=True, null=True)),
                ('vision', models.IntegerField(blank=True, null=True)),
                ('handling', models.IntegerField(blank=True, null=True)),
                ('reflexes', models.IntegerField(blank=True, null=True)),
                ('aerial', models.IntegerField(blank=True, null=True)),
                ('jumping', models.IntegerField(blank=True, null=True)),
                ('command', models.IntegerField(blank=True, null=True)),
                ('throwing', models.IntegerField(blank=True, null=True)),
                ('kicking', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.club')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
