# Generated by Django 4.2.4 on 2023-08-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aerial',
        ),
        migrations.RemoveField(
            model_name='player',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='player',
            name='crossing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='handling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='player',
            name='jumping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kicking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='long_shots',
        ),
        migrations.RemoveField(
            model_name='player',
            name='marking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='one_on_ones',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='positioning',
        ),
        migrations.RemoveField(
            model_name='player',
            name='reflexes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='set_pieces',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='player',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tackling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='player',
            name='throwing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='work_rate',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='Nicholson Michele', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=17),
        ),
    ]
