# Generated by Django 4.2.4 on 2024-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_position_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='endurance',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='line_play',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='reflexes',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Sean Turner', max_length=100),
        ),
    ]
