# Generated by Django 4.2.4 on 2024-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_endurance_player_line_play_player_passing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='line_play',
            new_name='work_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='endurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shooting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='speed',
        ),
        migrations.AddField(
            model_name='player',
            name='aerial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ball_control',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='command',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='crossing',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='handling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='heading',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jumping',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='kicking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='long_range',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='marking',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pace',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='positioning',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tackling',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='throwing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='vision',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Shawn Thomas', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='reflexes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
