# Generated by Django 4.2.4 on 2024-03-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_rename_line_play_player_work_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ball_control',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='crossing',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='heading',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_range',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='marking',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Todd Gray', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='positioning',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tackling',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
