# Generated by Django 4.2.4 on 2024-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_player_ball_control_alter_player_crossing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ball_control',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='crossing',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='heading',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_range',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='marking',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='James Martinez', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='positioning',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='stamina',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='strength',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tackling',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_rate',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
