# Generated by Django 4.2.4 on 2024-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_player_player_class_alter_player_ball_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='stadium_capacity',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_name',
            field=models.CharField(default='Stadium', max_length=100),
        ),
    ]
